version: "3"

services:
  database:
    image: mariadb
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./data:${DB_DATA_CONTAINER_PATH}
      - ./data/.mysql.d:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306
  
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: daoc-adminer
    ports:
      - 8080:8080

  daoc-server:
    build:
      ./DOLSharp
    container_name: daoc-server
    depends_on:
      - database
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./DOLSharp/Debug:/app
    ports:
      - 10300:10300
